### ISSUE TITLE
-vmodule should allow level -1

### ISSUE THREAD

**Issue by michael-db** [kubernetes/klog#107]
/kind bug

It is possible to pass the option  -v -1  to disable level 0 logging, in which case only Errors are logged. However, it is not possible to pass a negative number for logging in a particular module, i.e., with the  -vmodule  option.

**What steps did you take and what happened:**

: logtest 114;  go build && ./logtest -vmodule klogr=-1
invalid value "klogr=-1" for flag -vmodule: negative value for vmodule level

**What did you expect to happen:**

No error message, all log messages other than Errors for the specified module silenced.

**Anything else you would like to add:**

**Comment by neolit123** [comment]
> disable level 0 logging

which is essentially disable logging completely?
isn't there a flag to do that already?

**Comment by michael-db** [comment]
Is there? Level -1 applies only to Info, not Error, so it is not equivalent to disabling logging completely.
```
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
```
If I have missed something then could you please indicate how to use -vmodule to disable all Info logging, but not Error logging, for a particular module.

**Comment by michael-db** [comment]
```
: logtest 4;  go build && ./logtest -v -1
E1112 17:39:41.015022    1523 main.go:48]  "msg"="Error." "error"="oops"  
```
What is required is the equivalent with -vmodule to also work.

**Comment by neolit123** [comment]
>  Level -1 applies only to Info, not Error, so it is not equivalent to disabling logging completely.

yes, i guess that's true.

> If I have missed something then could you please indicate how to use -vmodule to disable all Info logging, but not Error logging, for a particular module.

ok, i think there is no way of doing that, currently.
the kind/feature label seems valid.

you can also try asking in #klog on the k8s slack if somebody has ideas.
