### ISSUE TITLE
Flag log_dir not work

### ISSUE THREAD

**Issue by silentred** [kubernetes/klog#108]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
main.go
```
package main

import (
	"k8s.io/klog"
)

func main() {
	klog.InitFlags(nil)
	klog.Info("start")
	klog.Flush()
}
```
go build -o main main.go
mkdir logs
./main -logtostderr=false -log_dir=logs

There is no log files under the dir "logs".

**What did you expect to happen:**
There are some files in the dir "logs"

**Comment by vanou** [comment]
You should call `flag.Parse()` to parse flag values passed at command line.

So following works
```
package main

import (
	"flag"
	"k8s.io/klog"
)

func main() {
	klog.InitFlags(nil)
	flag.Parse()
	klog.Info("start")
	klog.Flush()
}
```

**Comment by THMAIL** [comment]
> You should call `flag.Parse()` to parse flag values passed at command line.
> 
> So following works
> 
> ```
> package main
> 
> import (
> 	"flag"
> 	"k8s.io/klog"
> )
> 
> func main() {
> 	klog.InitFlags(nil)
> 	flag.Parse()
> 	klog.Info("start")
> 	klog.Flush()
> }
> ```

It's not work for me. I used the code you provided, and execute `go run main.go -log_dir=logs`. But nothing happened，the log dir is empty and the cmdline has output.
