### ISSUE TITLE
Make type loggingT public type

### ISSUE THREAD

**Issue by vanou** [kubernetes/klog#119]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
I would like to make type `loggingT` public type. Because I want to make importer of `klog` be able to handle multiple `logr.InfoLogger` & `logr.Logger`.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
* Make `loggingT` public type
* Modify code glued to `logging` global variable (e.g. method `setVState` of `loggingT`: it only refers to global variable `logging`) & add function/method to maintain backward compatibility.

**Comment by neolit123** [comment]
> Make loggingT public type

if loggingT is made public it now becomes a public API that must not be broken by changes.
given the state of klog my vote goes to not making it public.

> Modify code glued to logging global variable (e.g. method setVState of loggingT: it only refers to global variable logging) & add function/method to maintain backward compatibility.

the global "lggging" variable seems like a separate refactor that should be done regardless?

**Comment by vanou** [comment]
Thanks @neolit123 . Sorry for late reply.

> if loggingT is made public it now becomes a public API that must not be broken by changes.
given the state of klog my vote goes to not making it public.

You mean because current `klog` has many parts which should be improved/fixed, if `loggingT` is made public, it will slow speed of future development in `klog`?

> the global "logging" variable seems like a separate refactor that should be done regardless?

Yes.

> can you explain the use case in more detail?

My colleague wants to implement structured logging. Currently, one approach is to use `logr.Logger` / `logr.InfoLogger` with `klog`. However implementation of his idea will produce large amount of logs compared to current logs `klog` produces, because all of `klog` code in importer produce structured log. It can affect performance of kubernetes.
And I think if only part of, not all code of, `klog` importer code uses `logr.Logger` / `logr.InfoLogger`, amount of log increased by `logr.*` implementation can be reduced. (e.g. only call to creation/deletion of `Deployment` resource will be logged with structured log, because only part of kubernetes-apiserver code related to `Deployment` uses `klog` with his `logr.*` implementation)

However, in current `klog`, `SetLogger` function sets `logr` field of `logging` global variable. So every `klog` code in importer will use same `logr.*` implementation, even if only part of `klog` importer code want `logr.*`. If type `loggingT` is public, part of `klog` importer code use value of type `loggingT` which uses `logr.*` implementation and other part does not.

**Comment by neolit123** [comment]
> You mean because current klog has many parts which should be improved/fixed, if loggingT is made public, it will slow speed of future development in klog?

yes. by exposing it as public we are creating an API contract and i don't think loggingT (in it's current state) is suitable for that.

> My colleague wants to implement structured logging. Currently, one approach is to use logr.Logger / logr.InfoLogger with klog. However implementation of his idea will produce large amount of logs compared to current logs klog produces, because all of klog code in importer produce structured log. It can affect performance of kubernetes.

i'm wondering if this is already somehow supported and can be achieved without making loggingT public.

this example here gives you a separate `log` that is a structured:
https://github.com/kubernetes/klog/blob/master/examples/klogr/main.go#L19-L27

but how about running `klog.V(3).Infof` there as well; wouldn't that result in non-structured output?

i could be wrong and would appreciated more comments from others.
you can try asking in the #klog channel on k8s slack too.

**Comment by vanou** [comment]
> yes. by exposing it as public we are creating an API contract and i don't think loggingT (in it's current state) is suitable for that.

I understand. If there are works I can contribute to, I would like to do. Are there any roadmap in `klog`? Or should I start with issues not closed?

> i'm wondering if this is already somehow supported and can be achieved without making loggingT public.
> i could be wrong and would appreciated more comments from others. you can try asking in the #klog channel on k8s slack too.

Thanks. All `klogr` and `klog` depend on `logging` variable. So, currently, it looks difficult to handle multiple `logr.*`. I'll search any other workaround and will ask at slack channel.

**Comment by neolit123** [comment]
> I understand. If there are works I can contribute to, I would like to do. Are there any roadmap in klog? Or should I start with issues not closed?

i have a "reviewer" status for the klog project and i'm not aware of its roadmap.
maybe klog has to be re-written from scratch, or maybe k8s is going to want to switch to a new logger. for now we seem to be stuck with it.
