### ISSUE TITLE
Call to user.Current() crashes on Windows Nano

### ISSUE THREAD

**Issue by albertvaka** [kubernetes/klog#122]
/kind bug

**What steps did you take and what happened:**
The `init` function in `klog_file.go` [1] uses a Go API that doesn't work on Windows Nano [2], making every program that depends on klog crash on this platform. Note also that k8s is a primary target of Windows Nano, so this can be a common case.

**What did you expect to happen:**
This might eventually get fixed on Go's side, but since the issue [1] has been open for 3 years now it might be worth implementing a workaround on klog.

[1] https://github.com/golang/go/issues/21867
[2] https://github.com/kubernetes/klog/blob/master/klog_file.go#L58

**Comment by dims** [comment]
@albertvaka looks like a variation of the code in https://github.com/golang/go/issues/21867#issuecomment-375741005 would help here. Can you please file a PR and we can iterate there?

**Comment by neolit123** [comment]
i contributed parts of the go stdlib user package for windows.

> This might eventually get fixed on Go's side, but since the issue [1] has been open for 3 years now it might be worth implementing a workaround on klog.

i also participated in this discussion and handling the lack of certain libraries of Nano made it really difficult to do anything sane in stdlib.

overall nano is not a well supported subset of windows for go, but there is demand for it in the container world.

i will assign myself to try to send a fix for this unless @albertvaka objects.
for starters we can keep the user unknown on windows.

/assign
/priority important-soon
/kind bug

**Comment by albertvaka** [comment]
Thanks a lot folks 🙇 

 It might be worth also backporting the fix to glog :)

**Comment by neolit123** [comment]
> It might be worth also backporting the fix to glog :)

sadly we cannot do that. the idea of klog was so that we can have a maintainable (debatable) logger that we can change and fix the way we want. glog is "locked".
