### ISSUE TITLE
Remove glog dependency

### ISSUE THREAD

**Issue by tahsinrahman** [kubernetes/klog#129]
/kind bug

go.mod files are not updated in master. If you run `go mod tidy` it'll add glog dependency. It comes from the example file https://github.com/kubernetes/klog/blob/2bed4d00564ea4dbef273202eabb5020e97a5e1a/examples/coexist_glog/coexist_glog.go

ref: https://github.com/kubernetes/klog/pull/128#discussion_r396896714

**Comment by tanjunchen** [comment]
/assign
@neolit123  do we need to remove this ?
