### ISSUE TITLE
After klog v2.0.0 release there are broken dependencies 

### ISSUE THREAD

**Issue by biwwy0** [kubernetes/klog#138]
/kind bug

**What steps did you take and what happened:**
after running `dep ensure -update -v` in a go project I get the following:

```
Solving failure: No versions of k8s.io/utils met constraints:
	master: Could not introduce k8s.io/utils@master, as it requires package k8s.io/klog/v2 from k8s.io/klog, but in version v2.0.0 that package is missing.
	godocs-readme: Could not introduce k8s.io/utils@godocs-readme due to multiple problematic subpackages:
	Subpackage k8s.io/utils/buffer is missing. (Package is required by k8s.io/client-go@kubernetes-1.15.10.)	Subpackage k8s.io/utils/integer is missing. (Package is required by k8s.io/client-go@kubernetes-1.15.10.)	Subpackage k8s.io/utils/trace is missing. (Package is required by k8s.io/client-go@kubernetes-1.15.10.)
```

**What did you expect to happen:**
Having `import "k8s.io/klog/v2"` keep working as it is still used widely

**Anything else you would like to add:**
I see many projects still use `k8s.io/klog/v2` endpoint in their source for klog v2. It would be nice to keep it for backward compatibility.

**Comment by neolit123** [comment]
/assign @dims

> dep ensure -update -v in a go project I get the following:

i don't think the k8s project itself uses dep anymore, so not clear if it's considered supported.

> as it requires package k8s.io/klog/v2 from k8s.io/klog, but in version v2.0.0 that package is missing.

we just switched k/utils to klog/v2:
https://github.com/kubernetes/utils/pull/152

**Comment by biwwy0** [comment]
It's not `dep` specific many projects, so if `utils` is good, then `client-go` is good too. Guess all is good
