### ISSUE TITLE
klogr flatten logs some strings oddly

### ISSUE THREAD

**Issue by benmoss** [kubernetes/klog#139]
/kind bug

**What steps did you take and what happened:**
Had a klogr log something with `>` in the string, and saw it come out as `u003e`

**What did you expect to happen:**
Just prints the `>` character

**Anything else you would like to add:**
https://play.golang.org/p/xoZ7_N1tkUw

**Comment by neolit123** [comment]
it's because of this:
https://github.com/kubernetes/klog/blob/master/klogr/klogr.go#L142

and it needs the following fix:
https://stackoverflow.com/questions/28595664/how-to-stop-json-marshal-from-escaping-and

/help
/priority backlog
