### ISSUE TITLE
Documentation for `V()` appears to be backwards

### ISSUE THREAD

**Issue by mook-as** [kubernetes/klog#151]
/kind bug

**What steps did you take and what happened:**
Read the documentation and got confused by how `V()` works.

[It says](https://github.com/kubernetes/klog/blob/4cae117fdf5d65aeb3f638b8d8c87cd1cf8c8d41/klog.go#L1230-L1233) (for 2.0.0):

> If the level in the call to V is at least the value of -v, […] the V call will log.

This says that when the application is invoked with `-v 3`, then `V(4)` will log but `V(2)` will not.

The code actually says:
```golang
if logging.verbosity.get() >= level { … do logging … }
```

The is the opposite (`-v` is at least the value of `V()`), and is the typical interpretation for verbosity levels.

**What did you expect to happen:**

Given that the documentation says _at least_, I would expect that `V(n)` will log if `n` is greater than the value given on the command line.

**Anything else you would like to add:**
This appears to be carried over from `glog`.  Comparing against the C++ glog, that instead is documented from the other side; it has:

> `v` (`int`, default=0)
> Show all `VLOG(m)` messages for `m` less or equal the value of this flag.  Overridable by --vmodule.

Given the age of the comment, perhaps I'm just reading it weird? It may be a good idea to at least add examples to disambiguate the situation.

I'm happy to make a PR if people agree this is a thing that should be changed.

**Comment by neolit123** [comment]
hi,

> If the level in the call to V is at least the value of -v, […] the V call will log.

this statement doesn't seem valid. -v=5 will not allow V(6) calls to log.
a PR for fixing the documentation for V() is welcome.

/remove-kind bug
/kind documentation
/priority backlog
/help

**Comment by dims** [comment]
@mook-as yes please! thanks for yout attention
