### ISSUE TITLE
Unable to get klog at latest version

### ISSUE THREAD

**Issue by andy-caruso** [kubernetes/klog#163]
/kind bug

**What steps did you take and what happened:**
Ran `go get -u k8s.io/klog/v2@v2.1.0`

```
go: github.com/go-logr/logr upgrade => v0.2.0
# k8s.io/klog/v2
../../../pkg/mod/k8s.io/klog/v2@v2.1.0/klog.go:690:45: undefined: logr.InfoLogger
../../../pkg/mod/k8s.io/klog/v2@v2.1.0/klog.go:702:43: undefined: logr.InfoLogger
../../../pkg/mod/k8s.io/klog/v2@v2.1.0/klog.go:706:48: undefined: logr.InfoLogger
../../../pkg/mod/k8s.io/klog/v2@v2.1.0/klog.go:721:44: undefined: logr.InfoLogger
../../../pkg/mod/k8s.io/klog/v2@v2.1.0/klog.go:739:55: undefined: logr.InfoLogger
../../../pkg/mod/k8s.io/klog/v2@v2.1.0/klog.go:764:32: undefined: logr.InfoLogger
../../../pkg/mod/k8s.io/klog/v2@v2.1.0/klog.go:881:43: undefined: logr.InfoLogger
../../../pkg/mod/k8s.io/klog/v2@v2.1.0/klog.go:1234:10: undefined: logr.InfoLogger
```

**What did you expect to happen:**
Package to retrieve successfully

**Comment by andy-caruso** [comment]
This also happens with `go get  k8s.io/klog/v2@v2.1.0` (omitting `-u`)

**Comment by andy-caruso** [comment]
Whoops, this was due to my go.mod specifying an incompatible version. I'll file a ticket with the other packages that are affected by the logr release

**Comment by oomichi** [comment]
@andy-caruso 
Hello, I am facing this issue on cloud-provider-openstack CI system.
Could you give me the link of the ticket you are filling?

**Comment by andy-caruso** [comment]
We resolved this issue by removing `-u` from our calls to `go get`. I have not filed any other tickets.

**Comment by oomichi** [comment]
OK, thanks.
I got it.
