### ISSUE TITLE
Support --log_file_max_size for multiple log files

### ISSUE THREAD

**Issue by jianjuns** [kubernetes/klog#169]
/kind feature

**Describe the solution you'd like**
As of now, the --log_file_max_size parameter of klog takes effect only when a single log file is specified via --log-file. And when the specified log file reaches the max size limit, klog will simply clean up all existing log messages in the file. This behavior seems not very useful to keep logs within a specified size.
So, it will be great if klog can support configurable max file size even with multiple log files (without the --log-file parameter). Probably even better to support specifying max number of log files. With these, users can accurately control the size of logs and number of log files to be kept.

**Comment by chinglinwen** [comment]
Any news for this issue?

**Comment by jyz0309** [comment]
Any updates?
