### ISSUE TITLE
Decrease flushInterval or make it configurable

### ISSUE THREAD

**Issue by vincepri** [kubernetes/klog#18]
/kind feature

**Describe the solution you'd like**
The current `flushInterval` is set to 30s, which is a lot higher than usually expected. It's common to [adopt alternative strategies](https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/cmd/logutil.go#L46-L51) to flush more frequently. I'd be great to either decrease the default or make it configurable with a flag.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by dims** [comment]
Agreed! here's where we set it to 30 seconds https://github.com/kubernetes/klog/blob/master/klog.go#L939

**Comment by dims** [comment]
we could use the same flag `log-flush-frequency` from https://github.com/kubernetes-sigs/cluster-api/blob/master/cmd/clusterctl/cmd/logutil.go#L46-L51

**Comment by dims** [comment]
@DirectXMan12 Ack thanks!
