### ISSUE TITLE
Provide custom depth log functions

### ISSUE THREAD

**Issue by kiyonlin** [kubernetes/klog#180]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

After encapsulating `klog`, I found that the header information of the logs was my own log file. 

```bash
E0926 12:34:59.478940   36079 log.go:41] error
I0926 12:34:59.479097   36079 log.go:54] info 0
```

And it should be 
```bash
E0926 12:40:48.291660   36252 main.go:15] error
I0926 12:40:48.291813   36252 main.go:16] info 0
```

This is because calling depth is 0 by default. Can we provide `V(l).XxxDepth` and `XxxDepthf` functions in the package? 

BTW, I can submit a PR.

**Comment by pires** [comment]
I just ran into this myself.

**Comment by pires** [comment]
It seems there are already depth functions, eg `InfoDepth` but these are not implemented by `Verbose`. Any reason why?

**Comment by pires** [comment]
For whoever comes next, maybe this helps

```go
func Debugf(format string, args ...interface{}) {
    if klog.V(4).Enabled() {
      formattedArgs := fmt.Sprintf(format, args...)
      klog.InfoDepth(1, formattedArgs)
    }
}
```
