### ISSUE TITLE
Should klog/v2 be mentioned in the README

### ISSUE THREAD

**Issue by lilic** [kubernetes/klog#181]
/kind feature

**Describe the solution you'd like**
The readme does not have an example for klog/v2. Is this intentional or would adjusting those examples to klog/v2 be better for new users to use klog/v2 directly?

If yes, should we replace the 
> Replace imports for github.com/golang/glog with k8s.io/klog

with 
> Replace imports for github.com/golang/glog with k8s.io/klog/v2

https://github.com/kubernetes/klog#how-to-use-klog

Thanks!

**Comment by dims** [comment]
@lilic yes we should be. Can you please whip up a quick PR, happy to merge it.

**Comment by dims** [comment]
thanks a ton @lilic
