### ISSUE TITLE
Optional additional callstack skipping for klogr

### ISSUE THREAD

**Issue by avorima** [kubernetes/klog#201]
/kind feature

**Describe the solution you'd like**

Wrapping the klogr logger to extend it causes the caller info to point to where the wrap is implemented instead of where the line was logged.
It'd be nice to be able to configure an additional number of caller frames to skip.

If https://github.com/kubernetes/klog/pull/197 gets merged it could be added as an `Option`

```go
func WithCallerSkip(callerSkip int) Option {
	return func(l *klogger) {
		l.callerSkip = callerSkip
	}
}
```

**Anything else you would like to add:**

[zapr](https://github.com/go-logr/zapr/blob/master/zapr.go#L168) allows this implicitly via [AddCallerSkip](https://github.com/uber-go/zap/blob/master/options.go#L108).

**Comment by pohly** [comment]
This was resolved when implementing support for WithCallDepth in https://github.com/kubernetes/klog/pull/207

/close
