### ISSUE TITLE
Make info logging non-blocking

### ISSUE THREAD

**Issue by marseel** [kubernetes/klog#209]
/kind feature

**Describe the solution you'd like**
I would like to make it possible to make logging with info level non-blocking.
Draft idea: 
- Add buffer for logging with limit of X logs that can be stored. 
- If buffer is not full, add log to buffer
- If buffer is full, increment counter of skipped logs
- Every Y seconds check if some logs were skipped and log aggregated information like "Z info logs were skipped" with warning level. 

This change would make info logs best effort and non-blocking.

**Anything else you would like to add:**
During scalability tests of kubernetes, we've observed that logging can significantly degrade performance of masters. Under high load, logging was taking up to 10s.

**Comment by serathius** [comment]
Having info logs as non-blocking sounds reasonable assuming that we will not change the default behavior, but introduce a flag to maintain backward compatibility 
/cc @thockin @DirectXMan12 @dims 
WDYT?

**Comment by dims** [comment]
@serathius i'll let the others chime in first. my question would be, is there a prior art in some other logging library?

**Comment by wojtek-t** [comment]
>  my question would be, is there a prior art in some other logging library?

I don't know open-source logging libraries TBH, but I know that this is something we're doing internally.

**Comment by serathius** [comment]
@marseel Info log buffering was implemented in v1.23 kubernetes as part of JSON log format. Please check if this fulfills your requirements.

**Comment by serathius** [comment]
Closing as feature was implemented.
/close
