### ISSUE TITLE
logcheck: should not return error if no Go files are present

### ISSUE THREAD

**Issue by ehashman** [kubernetes/klog#214]
/kind bug

**What steps did you take and what happened:**

When running logcheck against a directory that contains no Go files, I get an error:

```
-: no Go files in /home/ehashman/src/k8s/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/pods
logcheck: error during loading
```

**What did you expect to happen:**

I would expect a directory with no Go files to pass the linter.

**Anything else you would like to add:**

/cc @adisky 
/priority important-longterm

**Comment by serathius** [comment]
@ehashman is problem mitigated by running linter against parent directories? For example now we run against `pkg/kubelet/...`. I think it skips packages without Go files.

**Comment by umangachapagain** [comment]
This issue blocks kubernetes/kubernetes/issues/102439 which is targeted for v1.22.

/remove-lifecycle stale

**Comment by daemon1024** [comment]
I would like to look into this 🤓 /assign

**Comment by shivanshu1333** [comment]
Hey @daemon1024 can you please give us a rough estimate as in how much time it will require to come up with a fix for this?
I'd suggest you to go through review comments of https://github.com/kubernetes/klog/pull/220, it will give you an idea about the expected fix.
https://github.com/kubernetes/kubernetes/pull/103293 is ready to merge and is blocked by this, if you need any help please feel free to ping us

**Comment by daemon1024** [comment]
@shivanshu1333 I have went through the relevant discussions. I am currently in process of setting up and reproducing it. I will have a fix or some concrete update by the end of the week. 
Thank You I will make sure to reach out if I face some issues.

**Comment by shivanshu1333** [comment]
That's awesome, thanks!

**Comment by liggitt** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/108159

/close
