### ISSUE TITLE
logcheck: should not skip Windows files

### ISSUE THREAD

**Issue by ehashman** [kubernetes/klog#215]
/kind bug

**What steps did you take and what happened:**

Right now, it seems that logcheck is unable to check Windows files. This is probably because there is a specified build tag of windows. Since the CI environment is not Windows-based, they are not built and hence not linted.

**What did you expect to happen:**

Files with `// +build windows` should be linted.

**Anything else you would like to add:**

/cc @adisky @BenTheElder 
/priority important-longterm

**Comment by BenTheElder** [comment]
Invoking it twice with `GOOS=linux`, `GOOS=windows` is probably sufficient.
We have similar precedent in `test/typecheck` (a custom "linter" to ensure kubernetes cross-compiles without actually building binaries)

**Comment by ehashman** [comment]
Aha!

/honk

**Comment by adisky** [comment]
closing this, the fix has been merged here
https://github.com/kubernetes/kubernetes/pull/99996
/close
