### ISSUE TITLE
logcheck: Add check for format string usage

### ISSUE THREAD

**Issue by adisky** [kubernetes/klog#218]
/kind feature

**Describe the solution you'd like**
Improve `logcheck` tool to check for format string usage in structured logging functions like `InfoS`, `ErrorS`.

**Anything else you would like to add:**
We are reporting error if found usage of unstructured klog functions [here](https://github.com/kubernetes/klog/blob/master/hack/tools/logcheck/main.go#L86). In similar way we need to report usage of format strings, the tool should report error on following line.
`klog.InfoS("pod %s started", podName)`

related to: https://github.com/kubernetes/kubernetes/issues/98975

**Comment by lauchokyip** [comment]
Hey @umangachapagain , can I try working on this? Thank You :)

**Comment by umangachapagain** [comment]
> Hey @umangachapagain , can I try working on this? Thank You :)

@lauchokyip sure.

/unassign me
/assign  @lauchokyip

**Comment by lauchokyip** [comment]
Thank You!

**Comment by lauchokyip** [comment]
@umangachapagain Sorry! I think I am getting busier so I don't think I would have time to work on this one. I will assign back to you
