### ISSUE TITLE
updated the OWNERS file to reflect ownership of k/klog

### ISSUE THREAD

**Issue by neolit123** [kubernetes/klog#222]
**Describe the solution you'd like**

when k/klog was originally created (as a fork of glog) the project was owned by SIG Arch, but later it was stated that this should be owned by SIG Instrumentation. klog is listed as a sub-project SIG instrumentation:
https://github.com/kubernetes/community/tree/master/sig-instrumentation#klog

but the OWNER file in this repository does not reflect the owning SIG and contains a list of volunteers, who are mostly inactive here:
https://github.com/kubernetes/klog/blob/master/OWNERS

it feels like it should be updated with SIG Instrumentation members that can monitory changes closely, especially such that are breaking.

/assign @dims @ehashman 
/kind cleanup
@kubernetes/sig-instrumentation-members

**Comment by ehashman** [comment]
We recently reviewed this as part of the SIG Instrumentation annual report. We noted subproject owners as @dims @thockin and @DirectXMan12 and we added @dims to the SIG Instrumentation roster.

We have an agenda item this week to discuss forming a logging WG. Perhaps we can discuss this further then. https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit#heading=h.cx8m0c4qz1jr

**Comment by dims** [comment]
@ehashman given what's in OWNERS now https://github.com/kubernetes/klog/blob/main/OWNERS what do you want to do here? i am happy to close it.

**Comment by pohly** [comment]
Are we sure everyone listed in OWNERS is still active and will respond to review resp. approve requests?

**Comment by ehashman** [comment]
@dims given who's in the OWNERS file now, many of whom have gone emeritus, we think this is still relevant. @serathius will run your maintainers script to update the list.

**Comment by serathius** [comment]
Done https://github.com/kubernetes/klog/pull/309
