### ISSUE TITLE
logcheck: Improve concurrency.

### ISSUE THREAD

**Issue by adisky** [kubernetes/klog#223]
/kind feature

**Describe the solution you'd like**
Currently logcheck is able to accept multiple packages. It parses and check them sequentially, for smaller no. of packages it is fine, but when we migrate a larger chunk of k/k codebase to structured logging this tool will take significant time in CI.  

To avoid this the tool should be able to parse and check multiple packages concurrently.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by umangachapagain** [comment]
`SingleChecker.Main()` reads the args directly and passes it to checker. The checker creates trees and runs analysis on each root found (in parallel).
Any ideas on how we run the checker in parallel for each user provided arg?

**Comment by adisky** [comment]
> checker

The analysis run function which is looping over files, make it to run concurrently.

**Comment by umangachapagain** [comment]
> The analysis run function which is looping over files. Can we try to make it to run concurrently?
>
From comment on analysis package - `The Run function should not call any of the Pass functions concurrently.`
In our run function for analysis, we use `pass.Report()` which as per this comment shouldn't be called concurrently.
I'm confused.

**Comment by adisky** [comment]
Thanks @umangachapagain for researching on it, can we try to pass all packages at once in the script to speed up the tool? https://github.com/kubernetes/kubernetes/blob/master/hack/verify-structured-logging.sh#L54-L57

**Comment by umangachapagain** [comment]
> Thanks @umangachapagain for researching on it, can we try to pass all packages at once in the script to speed up the tool? https://github.com/kubernetes/kubernetes/blob/master/hack/verify-structured-logging.sh#L54-L57
>
I roughly tested it with https://github.com/kubernetes/kubernetes/pull/100246 and saw a huge improvement.
Without this change the script took `7s` just for checking while with the change it took `<1s`.

**Comment by adisky** [comment]
I think we are good to close this issue.
It has been fixed by https://github.com/kubernetes/kubernetes/pull/100246
/close
