### ISSUE TITLE
update SetOutput example

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/klog#23]
`klog.SetOutput` is a bit of a footgun right now, severities above `INFO` will write to the "files" with fallthrough to the lower files, potentially leading to the same line being written as many as 4 times to the same writer.

I think the safest usage of this right now is probably something like:

```go
klog.SetOutput(ioutil.Discard)
klog.SetOutputBySeverity("INFO", myWriter)
```

This works pretty nicely, but probably need some more documentation. I initially just did:
```go
klog.SetOutput(myWriter)
```
which has surprising (duplicated) output in some cases

**Comment by simonpasquier** [comment]
I'm hitting the same kind of issue as I'm trying to build an adapter that would allow to get `klog` logs to a  `github.com/go-kit/kit` instance. It would be nice if there was an option to avoid the automatic fallthrough mechanism.

**Comment by DirectXMan12** [comment]
similar to #53
