### ISSUE TITLE
[]byte will use +%v through InfoS.

### ISSUE THREAD

**Issue by njuptlzf** [kubernetes/klog#236]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

```
klog.InfoS("[]byte", "b1", []byte("hello world"))
```
print:
I0508 19:35:13.452661   57319 testKlog.go:11] "[]byte" b1=[104 101 108 108 111 32 119 111 114 108 100]

**What did you expect to happen:**
I0508 19:37:01.473191    2045 testKlog.go:11] "[]byte" b1="hello world"

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
part of https://github.com/kubernetes/kubernetes/issues/101714
As k8s conducts structured log migration, `InfoS `is used more and more, but` []byte`, usually cooperates with %q `before `the migration, is it necessary to submit a PR so that []byte uses %q in InfoS?
Currently in InfoS, []byte uses %+v.
https://github.com/kubernetes/klog/blob/0cc9b8363efc89db73313bf618deeff8964c4a86/klog.go#L832
If the idea is approved, I will do it, otherwise I will probably continue to use `klog.InfoS("[]byte", "b1", string([]byte("hello world")))`.

**Comment by njuptlzf** [comment]
> Oops, sorry @njuptlzf for not notice this `If the idea is approved, I will do it, otherwise I will probably continue to use`.

Everything is for the development of the community, cheers. :)

**Comment by pohly** [comment]
This didn't solve the problem for JSON. There the byte slice will be dumped as a [base64 encoded string representation of the bytes](https://stackoverflow.com/a/34089818).

IMHO the right solution for byte slices that are meant to be treated like strings is to convert to string before logging.

Let's reopen to discuss this further. We may have to put this into the migration guide.

/reopen
/wg structured-logging

**Comment by shivanshu1333** [comment]
Thanks, @pohly for pointing this out, I agree with 

> the right solution for byte slices that are meant to be treated like strings is to convert to string before logging.

**Comment by pohly** [comment]
> We may have to put this into the migration guide.

We have that now, so let's assume that this is indeed resolved.
