### ISSUE TITLE
logr has tagged v1.0.0-rc1

### ISSUE THREAD

**Issue by thockin** [kubernetes/klog#241]
/kind feature

logr made BREAKING CHANGES for implementations to prep for 1.0.0

I know this impl was derived from glogr, so here's the glogr PR that adopts the new logr API changes: https://github.com/go-logr/glogr/pull/13 - this includes a bunch of perf-related changes too.

The changes are not THAT complicated.  Please feel free to shout if they don't make sense.

**Comment by dims** [comment]
looks like the diff for logr is as shown here: https://github.com/go-logr/logr/compare/v0.4.0...v1.0.0-rc1

**Comment by thockin** [comment]
https://github.com/go-logr/zapr/pull/28 is a more surgical example (but I
did spend a log of time on the glogr changes to make perf less terrible,
e.g. avoiding `json`)

**Comment by thockin** [comment]
logr v1.0.0 has been tagged.  No changes since rc1.

**Comment by morlay** [comment]
Hi. Have a new release？

Block https://github.com/kubernetes-sigs/controller-runtime/pull/1593

**Comment by pohly** [comment]
v2.20.0 uses logr v1.1.0.

/close
