### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by dims** [kubernetes/klog#244]
Steps and check list are here:
https://www.kubernetes.dev/resources/rename/

**Comment by spiffxp** [comment]
/wg naming
umbrella issue ref: https://github.com/kubernetes/org/issues/2222

For future reference it would be helpful if you can confirm you've walked through the checklist.  Noting for @kubernetes/owners that the instructions as posted at kubernetes.dev are not easily copy-pasteable into an issue body as a checklist.

That said, I took a quick grep through kubernetes/klog and kubernetes/test-infra, and can't see that you'll have any pre/post migration changes to make.  So +1 as a member of @kubernetes/owners 

Things I would suggest adding to the body:
```
- [x]  Once all non-disruptive tasks have been completed and disruptive tasks have been identified, assign the GitHub Management team (@kubernetes/owners) for approval.
- [ ] Once the issue has been approved, send a notice to your SIG’s mailing list about the potential branch rename.
- [ ] Rename the default branch from master to main using the GitHub UI by following the official instructions.
- [ ] Trial the local development experience with a pre-rename clone.
- [ ] Send a notice about the branch rename to your SIG’s mailing list. Include the link to the GitHub instructions to rename your local branch.
```

**Comment by dims** [comment]
Note to sig-instrumentation mailing list - https://groups.google.com/g/kubernetes-sig-instrumentation/c/GmdVotAvZTw/m/wgpOM35mAgAJ

**Comment by dims** [comment]
Done!
