### ISSUE TITLE
Structured logging for Warnings and Errors

### ISSUE THREAD

**Issue by paullaffitte** [kubernetes/klog#248]
/kind feature

**Describe the solution you'd like**

I would like to be able to call `klog.WarningS` or `klog.ErrorS` to do structured logging on warnings and errors too.

**Anything else you would like to add:**

It would have to work just the same way as `klog.InfoS`

**Comment by yuzhiquan** [comment]
We have an discussion about warnings in https://github.com/kubernetes/klog/pull/184 formerly, you can check this, and if you have any other idea, ket me known.
