### ISSUE TITLE
Credential redaction or generic output filters

### ISSUE THREAD

**Issue by awly** [kubernetes/klog#25]
/kind feature

**Describe the solution you'd like**
The goal is to prevent accidental logging of credentials.
Ideally this would be opt-out output filter for things that look like:
- JWT
- PEM-encoded private key
- bearer tokens

Filter would replace these with something like `--- REDACTED CREDENTIAL ---`.

Alternatively, allow arbitrary pluggable filters, something like:
```
func AddFilter(filter func(line string) string)
```

**Anything else you would like to add:**
Performance impact would be the main concern here.

cc @mikedanese @liggitt

**Comment by DirectXMan12** [comment]
This is a good use for structured logging plus standardized structured keys.
