### ISSUE TITLE
Add a new flag `logFilePerm`

### ISSUE THREAD

**Issue by PushkarJ** [kubernetes/klog#251]
/kind feature

**Describe the solution you'd like**
Today, `klog` defaults to `0666` as file permission, when [opening](https://github.com/kubernetes/klog/blob/main/klog_file.go#L157-L163) or [creating](https://golang.org/pkg/os/#Create) a file. 

Some compliance requirements, such as CIS benchmarks recommend, file permissions to be set minimally.
e.g. `0640`: `other` has no permissions on any files and `group` does not have `write` or `execute` permissions on any files

It would be beneficial in that regard:
- To add a new flag `logFilePerm` that allows users to set file permission optionally 
- To ensure backwards compatibility keep the default to current default i.e. `0666`
- Add validation logic and tests to ensure that value set in the flag is a valid file permission value

**Anything else you would like to add:**
I am happy to add a PR with this feature, but wanted to open the issue first, to hear some thoughts and comments before PR is ready. Especially, interested to hear thoughts on whether an equivalent flag should be added for log directory or not. 

PS: This is my first contribution to `klog` so please let me know if I did something wrong or if I am missing something :)

**Comment by dims** [comment]
cc @serathius

**Comment by PushkarJ** [comment]
It seems like dividing the work in two different tasks would make sense:

[ ] Adding the flag and applying the permissions provided as value if the flag is present, defaulting to 0666 if flag not defined or if provided value is invalid
[ ] Input validation of the permission value (first character of string begins with 0, next three characters can be in range 0 to 7, Total length of string can not exceed 4)

**Comment by serathius** [comment]
If you are targeting the kubernetes core components (apiserver scheduler controller manager etc), we are planning to drop file writing flags https://github.com/kubernetes/kubernetes/issues/99270#issuecomment-864605988

It might make more sense to not to invest more time in adding new flags to klog, but instead simplifying it.

**Comment by PushkarJ** [comment]
@serathius thanks for the context, I was not aware of this discussion :) 

This feature, was not intended for just k8s core components. One good example is the linked issue for antrea from @antoninbas . Is there a recommendation to manage file permissions outside of klog for such usecases?

**Comment by zwpaper** [comment]
@serathius , The idea of simplifying klog's flags is great! it is pity that only happened in component-base/log, how about adding some options to choose the klog flags, keeping the compatibility while be able to use only wanted flags.

if so I can raise a new issue for discussion and PR for implementation.
