### ISSUE TITLE
logr version problems

### ISSUE THREAD

**Issue by dan-lepage** [kubernetes/klog#253]
/kind bug

**What steps did you take and what happened:**

```bash
$ go get -u k8s.io/klog/v2
# k8s.io/klog/v2
../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:705:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:724:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:742:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:763:10: invalid operation: logr != nil (mismatched types logr.Logger and nil)
../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:782:11: invalid operation: loggr != nil (mismatched types logr.Logger and nil)
../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:783:3: undefined: logr.WithCallDepth
../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:794:11: invalid operation: loggr != nil (mismatched types logr.Logger and nil)
../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:795:3: undefined: logr.WithCallDepth
../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:915:9: invalid operation: log != nil (mismatched types logr.Logger and nil)
../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:919:4: undefined: logr.WithCallDepth
../go/pkg/mod/k8s.io/klog/v2@v2.10.0/klog.go:919:4: too many errors
```

**What did you expect to happen:**

I expected it to install 

**Anything else you would like to add:**

logr v1.0.0 was released two weeks ago and has breaking changes - in particular, logr.Logger is a struct now instead of an interface. Until klog is updated to account for those changes, it would be great if you could update your go.mod to exclude it.

**Comment by dims** [comment]
being discussed here https://github.com/kubernetes/klog/pull/242

**Comment by dan-lepage** [comment]
#242 is about upgrading to logr v1.0; I'm wondering if in the short term you'd consider adding `exclude github.com/go-logr/logr v1.0.0` to your `go.mod` so that installation works until #242 is merged and released.

**Comment by pohly** [comment]
v2.20.0 uses logr v1.1.0. One still has to be careful with `get get -u ./...` because all dependencies must switch to the new logr API.

/close
