### ISSUE TITLE
KObj + ObjectRef not logged as struct by zap

### ISSUE THREAD

**Issue by pohly** [kubernetes/klog#262]
/kind bug

**What steps did you take and what happened:**

I tried how the JSON format in Kubernetes prints ObjectRef, the struct returned by KObj, and found that it prints `<namespace>/<name>`, i.e. the same as the plain text format.

**What did you expect to happen:**

It is meant to be logged as struct with (`{"name":<name>, "namespace":<namespace>}`).

**Anything else you would like to add:**

Unit test in https://github.com/kubernetes/kubernetes/pull/104877

It works with logr/funcr because it ignores ObjectRef.String whereas zap.Any prefers that if found: https://github.com/uber-go/zap/blob/eaeb0fc72fd23af7969c9a9f39e51b66827507ca/field.go#L544-L548

**Comment by pohly** [comment]
Possible solutions:
- fork zap.Any in zapr and remove support for fmt.Stringer
- implement [`MarshalLogObject`](https://github.com/uber-go/zap/blob/eaeb0fc72fd23af7969c9a9f39e51b66827507ca/zapcore/marshaler.go#L30-L32) in klog

I prefer implementing `MarshalLogObject`. It's a clean solution that also should be faster than relying on reflection for the struct.

**Comment by pohly** [comment]
The solution with `MarshalLogObject` is in https://github.com/pohly/klog/commit/730ec78dc104db49e89e4d597dc93e6af3087474

That's part of [a branch](https://github.com/pohly/klog/commits/testinglogger-kobj2) where I already added the zap dependency. Output now is:
```
$ go test -v ./testinglogger/example/
=== RUN   TestKlog
    example_test.go:90: INFO hello world
    example_test.go:91: ERROR failed err="failed: some error"
    example_test.go:92: INFO verbosity 1
    example_test.go:93: INFO main/helper: with prefix
    example_test.go:94: INFO key/value pairs int=1 float=2 pair="(1, 2)" kobj="kube-system/sally" pod="kube-system/pod1" pod2="kube-system/pod1"
--- PASS: TestKlog (0.00s)
...
--- PASS: TestLogr (0.00s)
=== RUN   TestZapr
{"ts":1631256107286865435,"msg":"hello world"}
{"ts":1631256107286894001,"msg":"failed","error":"failed: some error"}
{"ts":1631256107286908736,"msg":"verbosity 1"}
{"ts":1631256107286915680,"msg":"with prefix"}
{"ts":1631256107286922358,"msg":"key/value pairs","int":1,"float":2,"pair":"(1, 2)","kobj":{"name":"sally","namespace":"kube-system"},"pod":{"name":"pod1","namespace":"kube-system"},"pod2":"kube-system/pod1"}
--- PASS: TestZapr (0.00s)
PASS
```

**Comment by pohly** [comment]
The (incomplete) solution with `logr.ObjectMarshaler` is in modified versions of logr, zapr, and klog and gets pulled together in https://github.com/kubernetes/kubernetes/pull/104877.

Needs further work:
- decide which parts of `zapcore.ObjectEncoder` we want to add to `logr`
- more tests

**Comment by thockin** [comment]
I don't hate the logr impl, but it seems convoluted and really aimed at zap.  I guess I'd want to see how, for example, glogr would implement it.

The klog impl is nice because it is very contained, even if it has a zap coupling internally.  I'd lean towards that - if/when string output goes away we can remove it and the Stringer methods?

**Comment by pohly** [comment]
Regarding removing support for `fmt.Stringer`: I don't like that because
- it's a breaking change in zapr and would have to be made optional, with support enabled by default
- when we disable support in Kubernetes, JSON formatting becomes different than how zap normally works, which means we need to educate developers about it and be more careful during code reviews to avoid accidentally logging more data than intended
- if string output is desired, `String()` needs to be invoked at the callsite, which "feels" like a workaround

**Comment by pohly** [comment]
> I don't hate the logr impl, but it seems convoluted and really aimed at zap.

One could also argue that it is the opposite: it enables non-zap loggers to offer similar functionality as zap.

> I guess I'd want to see how, for example, glogr would implement it.

I suppose the [type switch in funcr](https://github.com/go-logr/logr/blob/59f23134cf4fcc453d6a89a369ed252f1b08242c/funcr/funcr.go#L172-L207) could be extended to check for the interface. The actual implementation of the encoder interface then needs to fill a buffer with the values passed via the different calls and use that buffer as result for `prettyWithFlags`.

But this is a lot of work for not much gain, without a clear indication that users of klogr or funcr want that.

> The klog impl is nice because it is very contained, even if it has a zap coupling internally. I'd lean towards that - if/when string output goes away we can remove it and the Stringer methods?

I also prefer this solution.

**Comment by dims** [comment]
@liggitt can you please chime in? (folks who use just client-go will end up vendoring zapr from what i can tell)

**Comment by liggitt** [comment]
adding zap as a dep of klog doesn't seem great

**Comment by pohly** [comment]
> folks who use just client-go will end up vendoring zapr from what i can tell

They need zap (not zapr), and only the interface definitions. If they don't use the new interface, then none of zap is going to be compiled into binaries. Vendoring is going to be a bit more costly.

> adding zap as a dep of klog doesn't seem great

The alternatives aren't great either :cry:

**Comment by pohly** [comment]
I was wondering whether the zap maintainers could be convinced to put the interface definitions into a completely stand-alone module. Backward compatibility could be preserved by aliasing those types in zap and zapcore.

**Comment by pohly** [comment]
Yet another alternative:
- stop using the KObj/KRef code from klog in Kubernetes
- instead implement in-tree, for example in src/staging/k8s.io/component-base/logs, with the zap dependency

From a practical point of view that's worse for Kubernetes (need two imports for logging instead of one), but conceptually it might be cleaner (normal users of klog shouldn't need it, so perhaps it shouldn't have been added there to begin with).

**Comment by thockin** [comment]
I didn't consider the downstream implications for client-go.  I very much
want users of client-go to be able to pass in any logr.Logger they like.
We should not be dictating which log lib to use.  Ideally klog breaks the
explicit dep on  any implementation - neither glog nor zap nor anything.

Is this the ONLY reason klog would dep on zap?

**Comment by pohly** [comment]
> I very much want users of client-go to be able to pass in any logr.Logger they like.

That still works. The dependency on zap in klog is completely optional: if zap is not used as logger, the code is never used.

The bigger question is whether we want to support serialization as struct also with other loggers and if so, how. The new logr API would enable that.

**Comment by thockin** [comment]
> That still works. The dependency on zap in klog is completely optional: if
> zap is not used as logger, the code is never used.
>
I don't  understand - if the code is in klog, the deps are  required, even
if never used?

> The bigger question is whether we want to support serialization as struct
> also with other loggers and if so, how. The new logr API would enable that.
>
On the one hand, maybe we should just leave this as an implementation
decision for different LogSinks.  funcr chooses not to call .String(), zapr
does call it.   I don't think we can really force all implementations to
support a no-method mode for this particular type.

On the other hand, I know we are hoping to use zap, and we want the struct
format, so maybe  we should be leaning on zap to find a setup-time config
(e.g. hold a `map[reflect.Type]` which has values that are per-type config
params, like "for reflect.TypeOf(klog.KObj{}), do not use methods".  If it
is at setup time, we can eat that in the setup, which consumers who don't
use zap would never call.

**Comment by pohly** [comment]
> I don't  understand - if the code is in klog, the deps are  required, even if never used?

The dependency is only needed to build one method: `MarshalLogObject` (= https://github.com/kubernetes/klog/blob/b2c90829cb4c51bfddcc05826db9e05fba294356/klog.go#L1598-L1606) must take a `zapcore.ObjectEncoder` as parameter, otherwise `ObjectRef` doesn't implement the `zapcore.ObjectMarshaler` interface that zap checks for. Only zap checks for that interface. All other loggers ignore it.

> funcr chooses not to call .String(), zapr does call it.  I don't think we can really force all implementations to
support a no-method mode for this particular type.

Agreed. In the go-logr API proposal I am stating that ["Loggers are not required to support it"](https://github.com/pohly/logr/blob/ca15dec7dec08acec5226d4ea472088d16856ba6/logr.go#L481-L491). As you noted, funcr doesn't need to support it because it falls through directly to reflection.

> so maybe we should be leaning on zap to find a setup-time config
(e.g. hold a `map[reflect.Type]` which has values that are per-type config
params, like "for reflect.TypeOf(klog.KObj{}), do not use methods".

That doesn't fit well into the current type switch: https://github.com/uber-go/zap/blob/eaeb0fc72fd23af7969c9a9f39e51b66827507ca/field.go#L544-L548

**Comment by pohly** [comment]
What would fit into such a type switch is implementing a `logr.UseReflection` interface with a `LogWithReflection()` method that never gets called. The mere existence of that interface could be used by zapr to skip `String` for `ObjectRef`.

This feels a bit hacky, but perhaps it's the least evil solution. I can prototype that tomorrow.

**Comment by thockin** [comment]
Maybe we (I) need to step back and re-examine the experience we want.

I'd like to see use get to a  place where users of client-go can so something like:

```
import "k8s.io/client-go/kubernetes"

client := ... // you create a client somehow
client.SetLogger(myapp.MakeNewLogger())

// use client 
```

If `MakeNewLogger()` uses zap, fine, but if not my app should NOT have an indirect dependency on zap.

Within client-go we use klog.  IMO, that MUST NOT cause a dependency on zap.  We could fix that by not using klog or by not having klog depend on zap.

It seems to me that, today, a user who uses client-go must link klog and therefore must link glog.  Let's not make that again?

I'm not AGAINST  giving logr  a role in this, but it really feels like an impl-configuration problem rather than a logr problem.

**Comment by liggitt** [comment]
> Within client-go we use klog. IMO, that MUST NOT cause a dependency on zap.

strong agree

**Comment by dims** [comment]
> > Within client-go we use klog. IMO, that MUST NOT cause a dependency on zap.
> 
> strong agree

Me as well!

**Comment by pohly** [comment]
> The bigger question is whether we want to support serialization as struct also with other loggers and if so, how. The new logr API would enable that.

One additional argument why an interface like `zap.ObjectMarshaler` might be useful for logr: reflection cannot be used to log unexported fields. Just an observation, I'm not convinced yet myself that this is important enough to justify the effort of adding such an API.

**Comment by pohly** [comment]
Solved with `logr.Marshaler` support in zapr and `ObjectRef`.

/close
