### ISSUE TITLE
logcheck doesn't handle Exit* functions correctly

### ISSUE THREAD

**Issue by serathius** [kubernetes/klog#264]
/kind bug

klog defines set of functions Exit, Exitf, Exitln, ExitDepth. Those functions are not correctly handled by logcheck. https://github.com/kubernetes/kubernetes/pull/103293#issuecomment-885028839

**What steps did you take and what happened:**

When running logcheck to validate log calls, it reported Exitf as structured logging method
```
/home/prow/go/src/k8s.io/kubernetes/test/images/apparmor-loader/loader.go:64:3: structured logging function "Exitf" should not use format specifier "%s"
```

**What did you expect to happen:**

I would expect that logcheck will ignore this method when in `allow-unstructured` mode and report it as error only when `allow-unstructured` is off.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by luyou86** [comment]
could assign it to me?

**Comment by serathius** [comment]
/assign @luyou86 
Automation will only allows to assign issues to members of K8s org, but we can agree to unofficially assign it to you. Feel free to work on it.

**Comment by serathius** [comment]
Done

**Comment by serathius** [comment]
Please let me know if you need any help (and nag me if I don't respond, best to reach me via a K8s Slack)

**Comment by luyou86** [comment]
ok, thx
