### ISSUE TITLE
klog always logs verbosity 0 with component-base/logs

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/klog#294]
/kind bug

**What steps did you take and what happened:**

I'm currently trying to use `component-base/logs` in combination with controller-runtime in ClusterAPI (https://github.com/kubernetes-sigs/cluster-api/pull/6072).
When using `--logging-format=json` the log lines contain `v: 0` independent of the log level with which the line is actually logged.

**What did you expect to happen:**
Should log the verbosity with which the log line is logged.

**Anything else you would like to add:**
When component-base/logs the "log hierarchy" is roughly go-logr.Logger => klog => JSON logger (component-base/logs) => zap:
![image](https://user-images.githubusercontent.com/4662360/153864210-48b29f86-a5eb-4bc1-b17a-f5020890821f.png)

I think the log level get's lost here: https://github.com/kubernetes/klog/blob/main/klogr/klogr.go#L169-L173

**To reproduce**:
I've created a minimal controller here: https://github.com/sbueringer/cr-klog-issue (with k8s.io/component-base v0.23.3 and	k8s.io/klog/v2 v2.40.1)
The issue can be reproduced by running the controller against an arbitrary cluster (with Pods) via:
```
$  go run main.go --logging-format=json --v=4
...
{"ts":1644841271031.652,"caller":"cr-klog-issue/main.go:92","msg":"controller/pod: Verbosity 0","v":0,"reconciler group":"","reconciler kind":"Pod","name":"capi-kubeadm-control-plane-controller-manager-9769796f6-l8nf2","namespace":"capi-kubeadm-control-plane-system"}
{"ts":1644841271031.67,"caller":"cr-klog-issue/main.go:93","msg":"controller/pod: Verbosity 1","v":0,"reconciler group":"","reconciler kind":"Pod","name":"capi-kubeadm-control-plane-controller-manager-9769796f6-l8nf2","namespace":"capi-kubeadm-control-plane-system"}
{"ts":1644841271031.679,"caller":"cr-klog-issue/main.go:94","msg":"controller/pod: Verbosity 2","v":0,"reconciler group":"","reconciler kind":"Pod","name":"capi-kubeadm-control-plane-controller-manager-9769796f6-l8nf2","namespace":"capi-kubeadm-control-plane-system"}
{"ts":1644841271031.6858,"caller":"cr-klog-issue/main.go:95","msg":"controller/pod: Verbosity 3","v":0,"reconciler group":"","reconciler kind":"Pod","name":"capi-kubeadm-control-plane-controller-manager-9769796f6-l8nf2","namespace":"capi-kubeadm-control-plane-system"}
{"ts":1644841271031.693,"caller":"cr-klog-issue/main.go:96","msg":"controller/pod: Verbosity 4","v":0,"reconciler group":"","reconciler kind":"Pod","name":"capi-kubeadm-control-plane-controller-manager-9769796f6-l8nf2","namespace":"capi-kubeadm-control-plane-system"}
```

xref: Slack thread: https://kubernetes.slack.com/archives/CG3518SFJ/p1644596428193789

**Comment by sbueringer** [comment]
cc @dims @pohly

**Comment by sbueringer** [comment]
cc @fabriziopandini @killianmuldoon

**Comment by pohly** [comment]
/assign

I intend to add a unit test to the [new "test" package](https://github.com/kubernetes/klog/pull/287) for this and then fix it.

**Comment by sbueringer** [comment]
Happy to re-test with a branch/PR if it is helpful, but the issue seems to be relatively straightforward.

**Comment by fabriziopandini** [comment]
Thanks for the quick fix! awesome!
