### ISSUE TITLE
release strategy for logcheck

### ISSUE THREAD

**Issue by pohly** [kubernetes/klog#312]
/kind feature

Right now, logcheck doesn't get released "properly" (no tag, no release notes). Kubernetes imports it via the commit hash (https://github.com/kubernetes/kubernetes/blob/0ade4678a7ba527d22f6baa81034dea423267608/hack/tools/go.mod#L14).

We could:
- tag it with `hack/tools/v0.1.0`
- move it to a separate repo
- do nothing and keep importing it via hash

**Describe the solution you'd like**

According to the discussion in https://github.com/kubernetes/kubernetes/pull/108725#discussion_r829501945, a separate repo seems more appropriate. There is no technical reason why the tool is in klog and releases are easier when it is a stand-alone repo.

**Comment by pohly** [comment]
[Jordan's preference](https://github.com/kubernetes/kubernetes/pull/108159#discussion_r834295863) is to move it to a separate repo.

**Comment by dims** [comment]
+1 from me (separate repo)

**Comment by RinkiyaKeDad** [comment]
I can help with this. We'd need to create a PR to https://github.com/kubernetes/org for the repo request. Are we fine with simply taking the current code and starting fresh in a new repo, that is, not preserving the commit history?



/assign

**Comment by pohly** [comment]
Let's preserve history. Git can do it and there is valuable information in the commit history that shouldn't get lost.

I would to it with "git format-patch hack/tools/logcheck", mangling paths, and "git am". There are of course other options.

**Comment by dims** [comment]
@pohly need to poke the sig-instrumentation leads i think as they will be the owner?

**Comment by RinkiyaKeDad** [comment]
Yup, I can take care of that! Will continue this discussion about the repo name there.
