### ISSUE TITLE
Need some pointers for using klog in a specific way

### ISSUE THREAD

**Issue by santhosh12992** [kubernetes/klog#321]
Hi,

I am using cobra app along with klog and exporting the logs using the `log_file` args. There is a specific use case for me along with generating the log_file.

Along with the entire log_file generation, we need to create a separate log file which will have a subset of the `log_file` say, I need to create a extra log file to log the particular function's klog.Info logs. Is it possible to do that using klogs. I have looked into the code and found 'SetOutput' but that wont flush the output to `log_file`.

Your help is appreciated.
`
func main() {
	// gdcloudctl uses klog and flush is needed to ensure buffered logs lines are written to log file.
	defer klog.Flush()
        klog.V(1).Infof("---Initiated Klog----")
	if err := NewCommand().Execute(); err != nil {
		os.Exit(1)
	}
}

func prettyPrint(){
        klog.V(1).Infof("Connections: \n")
        klog.V(1).Infof("---Starting pretty print----")
}
`

Now I am able to see all the three log lines in the `log_file` but along with the log_file I like to create a separate log file to have the logs only for the `prettyPrint` function.

Your help is appreciated.

-Santhosh

**Comment by pohly** [comment]
This isn't supported by klog, and it seems to specific to your use case to implement it in klog.

Can you use `SetOutput` with a custom `io.Writer` that writes both to `log_file` and optionally into a separate file?

**Comment by pohly** [comment]
/close

Due to lack of feedback.
