### ISSUE TITLE
Support log metric

### ISSUE THREAD

**Issue by wavezhang** [kubernetes/klog#34]
/kind feature

**Describe the solution you'd like**
Collect log statistics and expose metric API.
collect information like TAG, log type, log detail, count etc. 

**Anything else you would like to add:**

**Comment by DirectXMan12** [comment]
not sure klog is the most appropriate place to do this.  Projects should probably be exposing errors separately, especially since not all errors get logged directly.

**Comment by wavezhang** [comment]
the “errors” here refer to use defined loglevel error

**Comment by DirectXMan12** [comment]
I'm not entirely clear on what general log metrics would gain.  What information are you trying to get that your log ingestion mechanism doesn't already provide?
