### ISSUE TITLE
How to set verbosity and calldepth for a logger

### ISSUE THREAD

**Issue by SQLJames** [kubernetes/klog#346]
Good afternoon, I am working on building a logging interface for one of my CLI tools. When trying to build this, I would need to change the verbosity level and the call depth. 
My Log functions are taking advantage of the Verbosity levels behind the abstraction, E.G. 
```
func (k *klogger) Info(message string, keysAndValues ...interface{}) {
     klog.V(2).InfoS(message, keysAndValues...)
}
func (k *klogger) Debug(message string, keysAndValues ...interface{}) {
	
	klog.V(4).InfoS(message, keysAndValues...)
}
func (k *klogger) Trace(message string, keysAndValues ...interface{}) {
	
	klog.V(5).InfoS(message, keysAndValues...)
}
```
However, because of this, I need to use the klog.InfoSDepth() function which allows me to change the depth of the log so it just doesnt show my log.go package file. However, the combination of both doesnt seem to be possible `klog.V(2).InfoSDepth()`

I tried to set the logger using 
``` 
	klog.SetLogger(
		klogr.New().WithCallDepth(1))
```
However when doing this, I just have my application hang. Can someone offer some guidance on how to implement this?

**Comment by pohly** [comment]
> However, the combination of both doesnt seem to be possible klog.V(2).InfoSDepth()

Can you elaborate what you mean with "doesn't seem to be possible"? That combination exists.

> klog.SetLogger(
>		klogr.New().WithCallDepth(1))

Indeed, that will lead to klog calling itself, which either deadlocks or loops infinitely (probably the former).

**Comment by SQLJames** [comment]
> Can you elaborate what you mean with "doesn't seem to be possible"? That combination exists.

Actually it seems like I was using an older version, I am not fully sure how that happened considering it is a new project. It does work now that I am using the latest version.
 
> Indeed, that will lead to klog calling itself, which either deadlocks or loops infinitely (probably the former).
I am still having a hard time with initializing the logger. even without the WithCallDepth option it hangs on writing out the infoSDepth or Info
In a new file I am just calling this to test it.
``` 
	klog.SetLogger(klogr.New())
	klog.V(0).InfoSDepth(1, "test")
```

**Comment by pohly** [comment]
> `klog.SetLogger(klogr.New())`

Just don't do that. You are telling klog to write to a logger which writes to klog, which writes to the logger, which ....

**Comment by SQLJames** [comment]
Ah you were saying it wasn't the `.WithCallDepth(1))` option but instead setting the `klog.New()` option inside of the set logger. 
Sorry there are alot of references to logger in this package, I do have it figured out now.  

```
klog.SetLogger(klog.LoggerWithValues(zapr.NewLogger(zaplog), "applicationName", "").WithCallDepth(1))
```
