### ISSUE TITLE
add a `loglevel` for verbosity

### ISSUE THREAD

**Issue by dims** [kubernetes/klog#35]
Request from @soltysh at:
https://github.com/kubernetes/kubernetes/issues/35054#issuecomment-255750857

```
I'd propose loglevel, we are already doing that downstream in OpenShift, see here. As for docs we can use this https://github.com/kubernetes/kubernetes/blob/master/docs/devel/logging.md with extra information about levels 7, 8 which allow you to dump HTTP requets.
```

**Comment by dims** [comment]
the current logging conventions are here https://github.com/kubernetes/community/blob/master/contributors/devel/logging.md

**Comment by discordianfish** [comment]
Its https://git.k8s.io/community/contributors/devel/sig-instrumentation/logging.md now

**Comment by discordianfish** [comment]
Just a FYI: Doesn't look like apiserver follows these conventions. Just started apiserver with -v=2 and I don't see it logging requests. -v=3 seems to do.

**Comment by neolit123** [comment]
hi, is this ticket about adding `--loglevel` as an alias to the already existing `--v` flag?
/kind feature
/priority backlog

**Comment by dims** [comment]
@neolit123 yep
