### ISSUE TITLE
Add logging reference format with Group, Version, Kind, Namespace and Name

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes/klog#350]
It would be useful to have  klog reference format that includes all of the information about a resource required to identify it - i.e. Group, Version, Kind, Namespace and Name. 

Would it be possible to add a type that holds all of this information (or to add fields to an existing type e.g. KRef)?

This ask comes from [usage of klog in Cluster API](https://github.com/kubernetes-sigs/cluster-api/issues/7150) where full references including kind etc. are needed for related objects e.g. the OwnerRef of the principle object. The struct would be useful as it allows correct logging of the full type information using both text and json logging.

This is what Cluster API has currently:
```
// logRef is used to correctly render a reference with GroupVersionKind, Namespace and Name for both JSON and text logging.
type logRef struct {
	Group     string `json:"group,omitempty"`
	Version   string `json:"version,omitempty"`
	Kind      string `json:"kind,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	Name      string `json:"name,omitempty"`
}

func (l logRef) String() string {
	var parts []string
	for _, s := range []string{l.Group, l.Version, l.Kind, l.Namespace, l.Name} {
		if strings.TrimSpace(s) != "" {
			parts = append(parts, s)
		}
	}
	return strings.Join(parts, "/")
}

// MarshalLog ensures that loggers with support for structured output will log
// as a struct by removing the String method via a custom type.
func (l logRef) MarshalLog() interface{} {
	type logRefWithoutStringFunc logRef
	return logRefWithoutStringFunc(l)
}

```

/kind feature

**Comment by pohly** [comment]
This might be a reasonable addition. What API did you have in mind for creating such a struct?

**Comment by pohly** [comment]
We cannot change `KRef`, changing its behavior would be unexpected for some users. `KResourceRef` sounds good to me.

If you want to give it a try, feel free to prepare a PR. However, no promise that it then will really get merged.

**Comment by killianmuldoon** [comment]
Would still like to include this if we can get an agreement on the API over at https://github.com/kubernetes/klog/pull/351

/reopen

**Comment by pohly** [comment]
/unassign

I don't have time to drive this.
