### ISSUE TITLE
 An extra line break was output 

### ISSUE THREAD

**Issue by aimuz** [kubernetes/klog#370]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

This is a log without SetLogger 

```
I0217 18:17:05.411664   62273 shared_informer.go:280] Caches are synced for project-controller
I0217 18:17:05.411821   62273 shared_informer.go:280] Caches are synced for application-controller
```

This is set by SetLogger 

```
2023-02-17T18:18:12.680+0800    INFO    client-go       Waiting for caches to sync for application-controller

2023-02-17T18:18:12.680+0800    INFO    client-go       Waiting for caches to sync for project-controller

2023-02-17T18:18:12.781+0800    INFO    client-go       Caches are synced for project-controller

2023-02-17T18:18:12.781+0800    INFO    client-go       Caches are synced for application-controller


```

They output a new line between them. After my investigation, I found that klog adds a new line at the end of the msg, but for the log output by the logr, the new line will be automatically added.

He can work normally under stdout, because stdout needs this newline

https://github.com/kubernetes/klog/blob/main/klog.go#L729

**What did you expect to happen:**

 Do not add new lines when using logr 

```
2023-02-17T18:18:12.680+0800    INFO    client-go       Waiting for caches to sync for application-controller
2023-02-17T18:18:12.680+0800    INFO    client-go       Waiting for caches to sync for project-controller
2023-02-17T18:18:12.781+0800    INFO    client-go       Caches are synced for project-controller
2023-02-17T18:18:12.781+0800    INFO    client-go       Caches are synced for application-controller
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by pohly** [comment]
Which `logr.Logger` implementation is this? If a trailing newline in the message string leads to undesired output, can't that implementation strip it out?

There's nothing in the `go-logr` API that says that the message string shouldn't end in a newline. As it's unspecified, I would expect the LogSink to deal well with both cases (newline and no newline).

**Comment by aimuz** [comment]
> Which logr.Logger implementation is this? If a trailing newline in the message string leads to undesired output, can't that implementation strip it out?

I don't think it's a question of whether to delete it or not, it's not normal behavior for a log library to always delete the last newline (which itself needs to output newlines?)

The problem with klog is that it adds newlines to all logs. For example, if you want to output "hello world", klog will process it as "hello world\n" and then call the logr implementation. It is normal to use the logr implementation because stdout or stderr require newlines, but that is only their


Now the logic

```
step1: klog.Info("hello world")
step2: msg = msg + "\n"
step3: stdout.W(msg) or logr.Info(msg)
```

He thought their ideal logic would be something like this

```
step1: klog.Info("hello world")
step3: stdout.W(msg+"\n") or logr.Info(msg)
```

**Comment by pohly** [comment]
If it's not making the code flow more complex in klog, then I am open to merging a PR which solves this in klog. But if it's complex, then the question stands whether a solution elsewhere might be possible.
