### ISSUE TITLE
flag set error : log to file or stderr 

### ISSUE THREAD

**Issue by THMAIL** [kubernetes/klog#371]
/kind bug

**What steps did you take and what happened:**
I try to save log to local file with parameter ：`go run main.go -log_dir=logs -logtostderr=false `
But errorLogs still will print to stderr!(infoLogs won't)
As the doc say `"stderrthreshold : logs at or above this threshold go to stderr when writing to files and stderr (no effect when -logtostderr=true or -alsologtostderr=false`.
So I tried `go run main.go -log_dir=logs -logtostderr=false -alsologtostderr=true -stderrthreshold=2` and `go run main.go -log_dir=logs -logtostderr=false -alsologtostderr=true -stderrthreshold=3`, but it doesn't work at all. 
The errorLogs still print to stderr.
So I analyzed the code of klog， finally I find that ：
```
if alsoToStderr || l.alsoToStderr || s >= l.stderrThreshold.get() {
	os.Stderr.Write(data)
}
```
in `klog.go` file `Line 20`.
this code tell me I should set alsoToStderr to false, then the stderrThreshold can come into effect. This is contrary to what the documentation says！
I tried `go run main.go -log_dir=logs -logtostderr=false -alsologtostderr=false -stderrthreshold=3`. It worked ! the errorLog didn't  print to stderr.

**What did you expect to happen:**
please fix this bug or just update the doc, it's up to you.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by pohly** [comment]
The code is the source of truth for this, because users might rely on this behavior.

Can you propose a PR which fixes the docs?
