### ISSUE TITLE
Sync with golang/glog

### ISSUE THREAD

**Issue by mrueg** [kubernetes/klog#372]
/kind feature

**Describe the solution you'd like**
It looks like google synced their internal glog with golang/glog last week: https://github.com/golang/glog/commit/115d1f9172402af5d19c22bb21c1d90686fa8b20

Consider adding the new exported APIs to ensure klog remains compatible with glog.

**Anything else you would like to add:**

From the commit message:
```
In particular this adds:

- New exported APIs (see godoc for further details):
  - glog.VDepth
  - glog.InfoDepthf
  - glog.WarningDepthf
  - glog.ErrorDepthf
  - glog.FatalDepthf
  - glog.ExitDepthf
  - glog.Names
  - glog.NewStandardLogger
  - glog.Verbose.InfoDepth
  - glog.Verbose.InfoDepthf
  - glog.ErrNoLog

- The -log_backtrace_at flag accepts now a comma-separated list of file:line locations.

- The -vmodule flag accepts a new syntax to match the full path to a module instead of just the module name. See the updated package documentation.

- A new internal/logsink package to support other outputs than files. Note: This package is internal, because we cannot guarantee at this point that the API remains stable.
```

**Comment by dims** [comment]
please no @mrueg ! we are way past glog.

/close

**Comment by mrueg** [comment]
@dims Fair point! :) Do the migration steps from to klog from glog need an update?

**Comment by dims** [comment]
@mrueg i don't remember us having a migration doc, could you share the link please?
