### ISSUE TITLE
Make (also)logtostderr default to true

### ISSUE THREAD

**Issue by vincepri** [kubernetes/klog#38]
/kind feature

**Describe the solution you'd like**
I'd like to propose that `logtostderr` or `alsologtostderr` be defaulting to true. It's very common in the k8s community to have `init()` or `main()` functions to hardcode the flag to "true", flipping the default value of either flag should ease the use of this package and remove some initial friction for new users.

**Anything else you would like to add:**

**Comment by DirectXMan12** [comment]
:+1: on this -- it's generally surprising for new users not to have this be the case, and as is mentioned, many things default this to `true` anyway (e.g. https://github.com/kubernetes/component-base/blob/master/logs/logs.go#L37, which enables it for anything in k8s.io/kubernetes, and a bunch of other things by accident).

**Comment by vincepri** [comment]
Opened a PR for this, feel free to put a hold on it if we need further discussion.
