### ISSUE TITLE
Can a function be added to the LogFilter？——Filterln 

### ISSUE THREAD

**Issue by jiegengH** [kubernetes/klog#381]
hope:
type LogFilter interface {
	Filter(args []interface{}) []interface{}
        Filterln(args []interface{}) []interface{}
	FilterF(format string, args []interface{}) (string, []interface{})
	FilterS(msg string, keysAndValues []interface{}) (string, []interface{})
}

Actual:
I want to desensitize my log information. If there is a Filterln, the format will be more rigorous.
But now, i must like this

func (k *KlogFilter) Filter(args []any) []any {
	pc, _, _, _ := runtime.Caller(1)
	function := runtime.FuncForPC(pc)
	name := function.Name()
	result := make([]any, 1)
	if strings.Contains(name, "printlnDepth") {
		result[0] = desensitize(fmt.Sprintln(args...))
	} else {
		result[0] = desensitize(fmt.Sprint(args...))
	}
	return result
}

**Comment by logicalhan** [comment]
/triage accepted
/assign @pohly 

> The `LogFilter` interface is part of the klog v2 API. We cannot change it without doing a v3, which isn't justified.

Should we just close this then?

**Comment by pohly** [comment]
I was giving @jiegengH some time to comment, but I agree, let's close it.

/close
