### ISSUE TITLE
log_max_file_num support

### ISSUE THREAD

**Issue by zk-123** [kubernetes/klog#385]
/kind feature

**Describe the solution you'd like**
When I use klog as my logging component, it generates a large number of info logs, which quickly fill up the disk. It would be very effective to have a parameter like `log_max_num` to control the number of historical log files to keep, only retaining the most recent ones. My understanding is that it requires periodically checking the number of historical log files and deleting old files that exceed `log_max_file_num`.

**Comment by pohly** [comment]
klog is in feature freeze. Please consider moving to a different backend which provides what you are looking for. `klog.SetLoggerWithOptions(logger, klog.ContextualLogger(true))` together with a full `logr.Logger` implementation can be used to completely replace klog.

**Comment by zk-123** [comment]
oh~
