### ISSUE TITLE
Support setting log level dynamically

### ISSUE THREAD

**Issue by astraw99** [kubernetes/klog#386]
/kind feature

**Describe the solution you'd like**
Currently the `klog` log level is set by `--v=3`, it is not supported to change the level without restarting the pod/container.
propose: expose a http endpoint like `curl localhost:10257/log?level=debug` to achieve it.

**Anything else you would like to add:**
The http endpoint port can use the same port if the container has already exposed a port.

**Comment by pohly** [comment]
I don't think that klog should get into the business of serving web requests.

Such a feature can be implemented on top of klog because the `-v` flag can be `Set` at runtime.

**Comment by astraw99** [comment]
Not just in serving web requests.
Currently in the K8s related controller, need to adjust the log level at runtime without restarting, how to?

**Comment by pohly** [comment]
Are you talking about some Kubernetes component or some arbitrary other controller written by someone?

The owner of that component would be responsible for enabling an API. If there is common code needed for this, then some shared repository could get created for that code. I still don't think that this should be in klog. Extending the klog API is tricky.

**Comment by astraw99** [comment]
Got it, thanks.
