### ISSUE TITLE
Why klog?

### ISSUE THREAD

**Issue by filmil** [kubernetes/klog#43]
/kind bug

It would be nice for the README file for `klog` to explain why the fork, versus contributing to glog.

**Comment by aledbf** [comment]
@filmil maybe because the glog [README](https://github.com/golang/glog/blob/master/README) contains
`The code in this repo is for export only and is not itself under development. Feature requests will be ignored.`

**Comment by filmil** [comment]
That explains just what it is, not why it is. :)

I would expect a sentence like: "We forked glog because..."

**Comment by dims** [comment]
please see
- https://github.com/kubernetes/kubernetes/issues/61006
- https://github.com/kubernetes/kubernetes/issues/70264
- https://groups.google.com/d/msg/kubernetes-sig-architecture/wCWiWf3Juzs/hXRVBH90CgAJ
- https://groups.google.com/d/msg/kubernetes-dev/7vnijOMhLS0/1oRiNtigBgAJ

**Comment by jaredallard** [comment]
I'm going to try to get this done by EOD Friday, if anyone else plans on working on this please @ me so that we don't duplicate efforts!
