### ISSUE TITLE
Bootstrapping a team to take care of klog

### ISSUE THREAD

**Issue by dims** [kubernetes/klog#44]
The following folks have expressed interested on email/slack:
https://groups.google.com/forum/#!msg/kubernetes-dev/DKWQn2a3Ybw/Z-07nwabDwAJ

@yagonobre 
@vincepri 
@detiber 
@jaredallard

Anyone else?

**Comment by dims** [comment]
@pohly how about you?

**Comment by jaredallard** [comment]
Just to reaffirm my interest, not a member of Kubernetes repo, so I hope that's not an issue.... but I have contributed to other k8s projects!

**Comment by VineethReddy02** [comment]
i would like to volunteer for this, but am new to the community. let me know if anything can be done from myside.

**Comment by justinsb** [comment]
Sign me up!  @justinsb

**Comment by pohly** [comment]
Davanum Srinivas <notifications@github.com> writes:
> @pohly how about you?

Okay.

Bye, Patrick

**Comment by neolit123** [comment]
me too. i've been watching this repo anyhow.

**Comment by dims** [comment]
Thanks everyone, i'll file a PR in a day or so.

**Comment by andyxning** [comment]
@dims I will also willing to do this. :) Please add me to reviewers also.

**Comment by hoegaarden** [comment]
Would be interested to ramp up and help out.
Bye, Hannes

**Comment by ttousai** [comment]
@dims I'm interested in contributing to klog.

**Comment by jayunit100** [comment]
@dims I recently was working on cleaning up klog issues in sig-storage and definetly want to help more , I’m happy to sign me up as a reviewer.

**Comment by ghShu** [comment]
@dims I have been in k8s channel for a while and recently started using k8s in projects. Although not a member of k8s repo yet, I am interested and happy to help the effort of taking care of klog.

**Comment by DirectXMan12** [comment]
I'm interested (@DirectXMan12) -- I've been reviewing stuff here so far and continue to be generally interested in the future of our logging libraries.

**Comment by dims** [comment]
@justinsb @DirectXMan12  : you are already an approver in the OWNERS file!

@ttousai @ghShu @andyxning @VineethReddy02 - please read through the history in mailing list and older issues (https://github.com/kubernetes/klog/issues/43#issuecomment-462437688) and file PRs / Issues etc. Once you are more active here or elsewhere in kubernetes, you can apply for org membership and we can add you as a reviewer after that ( https://github.com/kubernetes/community/blob/master/community-membership.md )

Everyone else, i'll file a PR right away with you all as reviewers, please cross check that and let me know if i miss anyone.

**Comment by DirectXMan12** [comment]
yep, just reiterating that I'm still interested :-)

**Comment by jaredallard** [comment]
@dims Assuming I'm included in that second list of people!

**Comment by dims** [comment]
@jaredallard yep! would love to see a PR that fixes #43 (hint!)

**Comment by andyxning** [comment]
@dims 

> @ttousai @ghShu @andyxning @VineethReddy02 - please read through the history in mailing list and older issues ([#43 (comment)](https://github.com/kubernetes/klog/issues/43#issuecomment-462437688)) and file PRs / Issues etc. Once you are more active here or elsewhere in kubernetes, you can apply for org membership and we can add you as a reviewer after that ( https://github.com/kubernetes/community/blob/master/community-membership.md )

I am already a Kubernetes member and being maintainer for some Kubernetes projects(kube-state-metrics/node-problem-detector). :) I think i already meet the requirement. :) Please re-consider it.
