### ISSUE TITLE
Confusing arguments

### ISSUE THREAD

**Issue by adrianlzt** [kubernetes/klog#54]
/kind bug

**What steps did you take and what happened:**
It is kinda difficult to configure logging, as arguments don't work as expected.

Doc is outdated and still show glog:
https://godoc.org/k8s.io/klog
```
-logtostderr=false
```

But in [code](https://github.com/kubernetes/klog/blob/master/klog.go#L413) is defaulted to ``true``:
```
flagset.BoolVar(&logging.toStderr, "logtostderr", true, "log to standard error instead of files")
```

Examples of weird behaviours.

No initialization shows >=error:
```
klog.Info("info")
klog.Error("error")
```

But if klog is initializated, it shows info and error (because flag ``logtostderr`` is set to true):
```
klog.InitFlags(nil)
flag.Parse()
klog.Info("info")
klog.Error("error")
```
Also weird because default value for stderrthreshold is ERROR and the doc says:
```
Log events at or above this severity are logged to standard error as well as to files
```

Then I switch off logging to stderr:
```
klog.InitFlags(nil)
flag.Set("logtostderr", "false")
flag.Parse()
klog.Info("info")
klog.Error("error")
```
And now it keeps logging to stderr but just error level.

**What did you expect to happen:**
Updated doc and a understandable behaviour.

**Comment by DirectXMan12** [comment]
There's two issues at play here:

1. The flag initialization issue (that's pretty sub-optimal)
2. The confusing nature of glog/klog flags and stderror -- that's a bit harder to fix due to backwards compat constraints, but we want to do it.  You're not the first person to be confused/frustrated by that.
