### ISSUE TITLE
klog adds additional global flags

### ISSUE THREAD

**Issue by liggitt** [kubernetes/klog#57]
**What steps did you take and what happened:**
klog 0.3.0 added a new global flag (`--log_file_max_size`). Global flags behave poorly in the presence of conflicting flags, or when a single binary links in multiple commands.

**What did you expect to happen:**
klog to provide an `AddFlags(flagSet)`-style mechanism for registering flags into a non-global flagset, rather than continuing to expand global flag registration in a way all downstream consumers have to react to.

**Comment by vincepri** [comment]
I'm mostly certainly missing something, but it seems to me that the expected behavior described above should be achievable today using https://github.com/kubernetes/klog/blob/master/klog.go#L407-L425 passing a FlagSet instead of nil.

**Comment by dims** [comment]
@vincepri context is the discussion in https://github.com/kubernetes/kubernetes/pull/76474#discussion-diff-274735802R108 on how kubelet is using stuff?

**Comment by BenTheElder** [comment]
/remove-lifecycle stale

ping! :upside_down_face:
