### ISSUE TITLE
Need benchmark tests to prevent regressions

### ISSUE THREAD

**Issue by dims** [kubernetes/klog#70]
Please see https://github.com/kubernetes/klog/issues/53 especially the comment from [Jordan](https://github.com/kubernetes/klog/issues/53#issuecomment-501374243) 

Also see https://github.com/kubernetes/kubernetes/issues/78734

**Comment by DirectXMan12** [comment]
/priority important-longterm

I can never remember the kinds (beyond `feature` and `bug`) without looking at the labels (which I can't on this repo).  Do we have an "infra" one?

**Comment by BenTheElder** [comment]
@DirectXMan12 find that frustrating too but you can actually look if you go to https://github.com/kubernetes/klog/labels (In the UI this is repo -> issues tab (all issues, not an issue) -> labels)

there's no infra label.

**Comment by DirectXMan12** [comment]
we'll call it

/kind cleanup

then

Thanks for the tip, I had forgotten that link was a thing

**Comment by dims** [comment]
we added one :)

/close
