### ISSUE TITLE
README.md dead link

### ISSUE THREAD

**Issue by michaelgugino** [kubernetes/klog#72]
/kind bug

https://github.com/kubernetes/klog/blame/master/README.md#L34

This link is 404.

**Comment by michaelgugino** [comment]
This is probably the correct link: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md

**Comment by neolit123** [comment]
seems resolved.
that line points to this now:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md

/close
