### ISSUE TITLE
Why not add "year" to log header or use well known time format?

### ISSUE THREAD

**Issue by yqwang-ms** [kubernetes/klog#86]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
https://github.com/kubernetes/klog/blob/3ca30a56d8a775276f9cdae009ba326fdc05af7f/klog.go#L622
Currently, the log header does not contain "year" info, so we cannot get the absolute time of each log line.
For example, we meet some problems:
1. We cannot distingush "I0809" is 2019/08/09 or 2018/08/09 when debugging
2. If the log is sinked to elastic search, and given 2 entries which is extracted from 2 log lines "I0101" and  "I1231", we cannot know which entry is the latest entry (i.e. the one with the largest timestamp).
3. 3rd log collector, such as docker or fluentd can append timestamp to each log line, but the collected timestamp is not so accurate as the logged timestamp. And this make klog hard depends on 3rd collector.

It is too uncommon to discard year but leave other timestamp in the log header.
So I hope if we can add the year to log header?

Moreover, can we use well known time format in log header, such as these in the Golang time package:
https://github.com/golang/go/blob/1dc0110bf725640a9b912e3d31e6654ed1c4da9d/src/time/format.go#L83

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by DirectXMan12** [comment]
changing this in the normal log output would be problematic for compatibility reasons.

**Comment by yqwang-ms** [comment]
@DirectXMan12 Thanks for this explanation.
But I'm thinking about, if, so why not continue to use glog and what is the propose of klog? I thought klog can revise a lot of historical problems in glog.

Why not make a flag in klog for this issue and the default value is disabled to be compatible, and let users can smoothly migrate to enable this flag instead of keeping historical problems forever?

**Comment by DirectXMan12** [comment]
klog is meant to fix some technical internal issues with glog.  However, we have to be careful with output issues -- whether we meant to or not, we've effectively formed a contract here with out users about log output.  Changing that without an option and deprecation period would cause issues.  That's not to say we can't change things -- we just have to make sure we allow a migration period.

**Comment by yqwang-ms** [comment]
Thanks @DirectXMan12 , totally agree!
So the only TBD is that, do we plan to provide "an option and deprecation period" for this issue?

Any comment?

**Comment by DirectXMan12** [comment]
we'd have to make it optional, yes

**Comment by DirectXMan12** [comment]
deprecation is unclear.  I suspect the default is sufficient for most people, but perhaps making the timestamp format customizable could be useful.

**Comment by yqwang-ms** [comment]
Yep, BTW, do you plan working on this? Or anyone else?
If not I can pick it up later when I am free :)

**Comment by DirectXMan12** [comment]
I don't have any plan to work on it.  You'll want to be careful that you don't introduce a perf regression when you do.

**Comment by yqwang-ms** [comment]
Thanks for the reminder! :)

**Comment by pecameron** [comment]
How about a callout function that the user can register to prepare the desired line prefix. For example, SetKlogPrefix( func prefix (... pass in existing context, time etc from klog, pass in byte vector to fill in). On each log call this function, when present, could get called. If the func is not set, today's processing is done.
This is one simple and optional API addition, and a simple call when the func is registered. The caller can fill the buffer as desired.
What do you think?
