### ISSUE TITLE
running klog as a dependency causes `read-only filesystem` errors

### ISSUE THREAD

**Issue by ilackarms** [kubernetes/klog#89]
/kind bug

**What steps did you take and what happened:**

Running a pod on Kube which has klog as an implicit dependency. Crashes on boot with `log: exiting because of error: log: cannot create log: open /tmp/gloo.gloo-7cbdc7dd4f-btkps.unknownuser.log.WARNING.20190813-140027.1: read-only file system`

Would like to know if there is a way to disable Klog from writing to disk?

**Comment by DirectXMan12** [comment]
questions are better directed @ discuss.k8s.io or stackoverflow.  However, to answer your question: `--logtostderr` will cause klog to log to standard error, and not a file.

**Comment by voidengineer** [comment]
This should not be closed!
As the reporter wrote, this is a bug. Klog should not write to /tmp (or anywhere else) if not explicitly enabled.

**Comment by DirectXMan12** [comment]
The reporter asked a question ("Would like to know if there is a way to disable Klog from writing to disk?").  The question was answered.  That's why the issue was closed.  If you'd like to discuss whether or not `logtostderr` should be the default, feel free to open an issue about that.
